FROM python:3.14-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    iptables net-tools iproute2 iputils-ping tshark \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY tests/fake_easy_aso_inst.py /app/
COPY pyproject.toml README.md LICENSE /app/
COPY easy_aso /app/easy_aso

RUN pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir /app

SHELL ["/bin/bash", "-c"]

CMD ["/bin/bash", "-c", "python3 fake_easy_aso_inst.py"]
