# Use a base image for Ubuntu 22.04
FROM ubuntu:latest

# Disable interactive prompts during package installation
ARG DEBIAN_FRONTEND=noninteractive

# Update Ubuntu repository and install necessary packages
RUN apt update && apt -y upgrade

# Install networking tools and Python
RUN apt install -y iptables net-tools iproute2 iputils-ping tshark
RUN apt install -y python3 python3-pip python3-venv

# Set working directory inside the container to /app
WORKDIR /app

# Create and activate a Python virtual environment
RUN python3 -m venv venv
RUN . /app/venv/bin/activate && python3 -m pip install bacpypes3 ifaddr

# Copy the fake BACnet server script to /app in the container
COPY tests/fake_bacnet_device.py /app/

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

# Command to run the fake BACnet server script with virtual environment activated
CMD ["/bin/bash", "-c", "source /app/venv/bin/activate && python3 fake_bacnet_device.py --name BensFakeAhu --instance 321"]
