# Download base image Ubuntu 22.04
FROM ubuntu:latest

# Disable prompt during packages installation
ARG DEBIAN_FRONTEND=noninteractive

# Update Ubuntu software repository and upgrade packages
RUN apt update && apt -y upgrade

# Install networking tools and Python
RUN apt install -y iptables net-tools iproute2 iputils-ping tshark
RUN apt install -y python3 python3-pip python3-venv

# Set working directory to /app
WORKDIR /app

# Create a Python virtual environment
RUN python3 -m venv venv

# Activate virtual environment and install bacpypes3 and ifaddr
RUN . /app/venv/bin/activate && python3 -m pip install bacpypes3 ifaddr

# Copy the server script from the tests directory
COPY tests/fake_bacnet_server.py /app/

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

# Command to run the fake AHU server script with virtual environment activated
CMD ["/bin/bash", "-c", "source /app/venv/bin/activate && python3 fake_bacnet_server.py --name BensFakeAhu --instance 3456789"]
