FROM python:3.14-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    iptables net-tools iproute2 iputils-ping tshark \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir bacpypes3 ifaddr

COPY tests/fake_bacnet_device.py /app/

SHELL ["/bin/bash", "-c"]

CMD ["/bin/bash", "-c", "python3 fake_bacnet_device.py --name BensFakeAhu --instance 321"]
