[CmdletBinding()]
param(
    [string]$OutFile = ".env.local"
)

$ErrorActionPreference = "Stop"

if (Test-Path -LiteralPath $OutFile) {
    throw "Refusing to overwrite existing file: $OutFile"
}

function New-HexToken([int]$bytes = 32) {
    $data = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($data)
    return ($data | ForEach-Object { $_.ToString("x2") }) -join ""
}

$bacnetKey = New-HexToken 32
$supervisorKey = New-HexToken 32

$content = @"
# Generated by scripts/bootstrap-secrets.ps1
BACNET_RPC_API_KEY=$bacnetKey
SUPERVISOR_API_KEY=$supervisorKey
"@
[System.IO.File]::WriteAllText($OutFile, $content, (New-Object System.Text.UTF8Encoding $false))

Write-Host "Wrote $OutFile with BACNET_RPC_API_KEY and SUPERVISOR_API_KEY"
Write-Host "Load into current shell:"
Write-Host "  Get-Content $OutFile | ForEach-Object { if (`$_ -match '^(.*?)=(.*)$') { Set-Item -Path Env:\$(`$matches[1]) -Value `$matches[2] } }"
