[CmdletBinding()]
param(
    [string]$OutFile = ".env.local"
)

$ErrorActionPreference = "Stop"

$resolvedOutFile = Resolve-Path -LiteralPath $OutFile -ErrorAction SilentlyContinue
if ($null -eq $resolvedOutFile) {
    if ([System.IO.Path]::IsPathRooted($OutFile)) {
        $resolvedOutFile = $OutFile
    } else {
        $resolvedOutFile = Join-Path (Get-Location) $OutFile
    }
} else {
    $resolvedOutFile = $resolvedOutFile.Path
}

if (Test-Path -LiteralPath $resolvedOutFile) {
    throw "Refusing to overwrite existing file: $resolvedOutFile"
}

function New-HexToken([int]$bytes = 32) {
    $data = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($data)
    return ($data | ForEach-Object { $_.ToString("x2") }) -join ""
}

$bacnetKey = New-HexToken 32
$supervisorKey = New-HexToken 32

$content = @"
# Generated by scripts/bootstrap-secrets.ps1
BACNET_RPC_API_KEY=$bacnetKey
SUPERVISOR_API_KEY=$supervisorKey
"@
[System.IO.File]::WriteAllText($resolvedOutFile, $content, (New-Object System.Text.UTF8Encoding $false))

Write-Host "Wrote $resolvedOutFile with BACNET_RPC_API_KEY and SUPERVISOR_API_KEY"
Write-Host "Load into current shell:"
Write-Host "  Get-Content $resolvedOutFile | ForEach-Object { if (`$_ -match '^(.*?)=(.*)$') { Set-Item -Path Env:\$(`$matches[1]) -Value `$matches[2] } }"
