#!/usr/bin/env python3
"""
Build a single PDF from the Easy ASO docs (Just the Docs / Jekyll-style Markdown).

Collects all docs/*.md (respecting nav_order and parent from YAML front matter),
strips front matter, concatenates with headings, and runs Pandoc to produce
pdf/easy-aso-docs.pdf. Also writes pdf/easy-aso-docs.txt (same Markdown source) for LLM context.

Adapted from open-fdd: https://github.com/bbartling/open-fdd/blob/master/scripts/build_docs_pdf.py
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_KRAMDOWN_IAL_RE = re.compile(r"\{:[^}\n]*\}\s*")

try:
    import yaml
except ImportError:
    yaml = None

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DOCS_DIR = REPO_ROOT / "docs"
PDF_DIR = REPO_ROOT / "pdf"
BUILD_DIR = DOCS_DIR / "_build"
DEFAULT_OUTPUT = PDF_DIR / "easy-aso-docs.pdf"


def parse_front_matter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = None
    for i in range(1, min(len(lines), 25)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, text
    yaml_block = "\n".join(lines[1:end])
    body = "\n".join(lines[end + 1 :]).lstrip()
    try:
        fm = yaml.safe_load(yaml_block) if yaml_block.strip() else {}
    except Exception:
        fm = {}
    return (fm or {}), body


def strip_kramdown_ial(text: str) -> str:
    return _KRAMDOWN_IAL_RE.sub("", text)


def collect_md_files(docs_dir: Path) -> list[Path]:
    out: list[Path] = []
    for f in sorted(docs_dir.rglob("*.md")):
        if f.name == "404.md":
            continue
        if "_build" in f.parts:
            continue
        out.append(f)
    return out


def section_order_key(
    path: Path,
    front_matter: dict,
    title_to_nav: dict[str, int],
) -> tuple[int, int, str]:
    parent = front_matter.get("parent") or ""
    nav = front_matter.get("nav_order")
    if nav is None:
        nav = 999
    try:
        nav = int(nav)
    except (TypeError, ValueError):
        nav = 999
    if parent:
        section_nav = title_to_nav.get(parent, 999)
    else:
        section_nav = nav
    return (section_nav, nav, str(path))


def build_title_to_nav(docs_dir: Path, files: list[Path]) -> dict[str, int]:
    title_to_nav: dict[str, int] = {}
    for path in files:
        fm, _ = parse_front_matter(path)
        title = fm.get("title")
        nav = fm.get("nav_order")
        if title and nav is not None:
            try:
                title_to_nav[title] = int(nav)
            except (TypeError, ValueError):
                pass
    return title_to_nav


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build Easy ASO docs into a single PDF (Pandoc + weasyprint or pdflatex)."
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output PDF path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--keep-md",
        action="store_true",
        help="Keep combined Markdown in docs/_build/combined.md",
    )
    parser.add_argument(
        "--pdf-engine",
        choices=["weasyprint", "pdflatex", "xelatex"],
        default="weasyprint",
        help="Pandoc PDF engine (default: weasyprint)",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Only write combined Markdown and .txt; do not run Pandoc",
    )
    args = parser.parse_args()

    if not DOCS_DIR.is_dir():
        print(f"Docs directory not found: {DOCS_DIR}", file=sys.stderr)
        return 1

    if yaml is None:
        print("PyYAML is required. pip install pyyaml", file=sys.stderr)
        return 1

    files = collect_md_files(DOCS_DIR)
    title_to_nav = build_title_to_nav(DOCS_DIR, files)

    def sort_key(path: Path) -> tuple[int, int, str]:
        fm, _ = parse_front_matter(path)
        return section_order_key(path, fm, title_to_nav)

    sorted_files = sorted(files, key=sort_key)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    combined_path = BUILD_DIR / "combined.md"
    now = datetime.now()
    build_date = now.strftime(f"%B {now.day}, %Y")
    parts: list[str] = []
    parts.append("% Easy ASO Documentation\n")
    parts.append("% Generated by scripts/build_docs_pdf.py\n")
    parts.append(f"% {build_date}\n\n")
    parts.append(f"*Generated {build_date}*\n\n")
    parts.append("---\n\n")

    for path in sorted_files:
        fm, body = parse_front_matter(path)
        title = fm.get("title") or path.stem.replace("-", " ").replace("_", " ").title()
        if fm.get("nav_exclude"):
            continue
        parts.append(f"# {title}\n\n")
        parts.append(strip_kramdown_ial(body))
        if not body.endswith("\n"):
            parts.append("\n")
        parts.append("\n\n")

    combined_md = "".join(parts)
    combined_path.write_text(combined_md, encoding="utf-8")
    print(f"Wrote {len(sorted_files)} pages to {combined_path}")

    txt_output = args.output.with_suffix(".txt")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    txt_output.write_text(combined_md, encoding="utf-8")
    print(f"Wrote LLM context text to {txt_output}")

    if args.no_pdf:
        print("Skipping PDF (--no-pdf).")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "pandoc",
        str(combined_path),
        "-o",
        str(args.output),
        "--toc",
        "--number-sections",
        f"--pdf-engine={args.pdf_engine}",
        "-V",
        "documentclass=article",
        "-V",
        "papersize=letter",
        "-V",
        "geometry:margin=1in",
        "-V",
        f"date={build_date}",
    ]
    print(f"Running: {' '.join(cmd)}")
    env = os.environ.copy()
    py_bin = str(Path(sys.executable).resolve().parent)
    if py_bin:
        env["PATH"] = py_bin + os.pathsep + env.get("PATH", "")
    try:
        subprocess.run(cmd, check=True, cwd=REPO_ROOT, env=env)
    except FileNotFoundError:
        print("pandoc not found. Install pandoc: https://pandoc.org/installing.html", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        if args.pdf_engine == "weasyprint":
            print("WeasyPrint PDF failed. pip install weasyprint", file=sys.stderr)
            print("Or use: python scripts/build_docs_pdf.py --pdf-engine=pdflatex", file=sys.stderr)
        return e.returncode

    print(f"PDF written to {args.output}")
    if not args.keep_md:
        combined_path.unlink(missing_ok=True)
    if BUILD_DIR.exists() and not any(BUILD_DIR.iterdir()):
        BUILD_DIR.rmdir()
    return 0


if __name__ == "__main__":
    sys.exit(main())
